#!/usr/bin/ruby

data = File.read 'program-data.js'

output = []

File.foreach './program-embed.html' do |line|
  if line != "<script id=\"program-data\" src=\"./program-data.js\"></script>\n" then
    output << line
  else
    output << "<script>\n" + data + "\n</script>\n"
  end
end

if !(File.exist? './dist') then
  `mkdir dist`
end

File.write './dist/program-embed.html', output.join("")
`cat ./dist/program-embed.html | pbcopy`

puts 'Output to ./dist/program-embed.html and copied to clipboard'
